% Function to save output data from inside of a 'parfor' loop. This is
% hacky, but required.

function parsave(power,ph_cnt,angle_mean,angle_var,distance_mean,distance_var,weight_mean,weight_var,num_photons,run_counter,reflected)
  save(sprintf('output%d.mat', run_counter),'power',...
      'ph_cnt',...
      'angle_mean','angle_var','distance_mean','distance_var',...
      'weight_mean','weight_var',...
      'num_photons','reflected','run_counter');
end
